myproject/mysite/urls.py
from django.contrib import admin
from django.urls import include, path

urlpatterns = [
    path("polls/", include("polls.urls")),
    path('admin/', admin.site.urls),
]

myproject/polls/urls.py
from django.urls import path
from . import views

app_name = "polls"
urlpatterns = [
    path("", views.index, name="index"),
    path("<int:question_id>/", views.detail, name="detail"),
    path("<int:question_id>/results/", views.results, name="results"),
    path("<int:question_id>/vote/", views.vote, name="vote"),
    path("login/", views.user_login, name="login"),  
    path("register/", views.register, name="register"),
    path("logout/", views.log_out, name="logout")
]

myproject/polls/models.py
import datetime
from django.db import models
from django.utils import timezone
from django.contrib.auth.models import User

class Question(models.Model):
    question_text = models.CharField(max_length=200)
    pub_date = models.DateTimeField("date published")

    def __str__(self):
        return self.question_text
    
    def was_published_recently(self):
        return self.pub_date >= timezone.now() - datetime.timedelta(days=1)

class Choice(models.Model):
    question = models.ForeignKey(Question, on_delete=models.CASCADE)
    choice_text = models.CharField(max_length=200)
    votes = models.IntegerField(default=0)

    def __str__(self):
        return self.choice_text

class PollUser(models.Model):
    user = models.OneToOneField(User, on_delete=models.CASCADE)
    country = models.CharField(max_length=50)
    phone = models.CharField(max_length=20)


    def __str__(self):
        return "{} {}".format(self.user.first_name, self.user.last_name)

class ApiKey(models.Model):
    username = models.CharField(max_length=50)
    api_key = models.CharField(max_length=20)

    def __str__(self):
        return "{} - {}".format(self.username, self.api_key)

myproject/polls/views.py
import random
import string
from django.shortcuts import get_object_or_404, render
from django.http import Http404

from .models import Question, Choice, PollUser, ApiKey
# Create your views here.
from django.contrib.auth.models import User
from django.contrib.auth import authenticate, login, logout
from django.http import HttpResponse, HttpResponseRedirect
from django.urls import reverse


def index(request):
    username = request.GET.get('username', '')
    api_key = request.GET.get('api_key', '')
    
    try:
        user = User.objects.get(username=username)
    except User.DoesNotExist:
        user = None

    if user:
        apk = ApiKey.objects.get(username=username)
        if apk.api_key == api_key:
            lq = Question.objects.order_by("-pub_date")[:5]
            context = {"latest_question_list": lq}

            context["user_info"] = user.first_name
            return render(request, "polls/index.html", context)
    else:
        return HttpResponse("Authentication credentials missed or not valid")

def detail(request, question_id):
    question = get_object_or_404(Question, pk=question_id)
    return render(request, "polls/detail.html", {"question": question})


def results(request, question_id):
    question = get_object_or_404(Question, pk=question_id)
    return render(request, "polls/results.html", {"question": question})


def vote(request, question_id):

    username = request.GET['username']
    api_key = request.GET['api_key']

    user = User.objects.get(username=username)
    if user:
        apk = ApiKey.objects.get(username=username)
        if apk.api_key == api_key:

            question = get_object_or_404(Question, pk=question_id)
            try:
                print("CHoice id - ", request.POST["choice"])
                selected_choice = question.choice_set.get(pk=request.POST["choice"])
            except (KeyError, Choice.DoesNotExist):
                # Redisplay the question voting form.
                return render(
                    request,
                    "polls/detail.html",
                    {
                        "question": question,
                        "error_message": "You didn't select a choice.",
                    },
                )
            else:
                print("S - ", selected_choice.votes)
                selected_choice.votes += 1
                selected_choice.save()
                print("E - ", selected_choice.votes)
                # Always return an HttpResponseRedirect after successfully dealing
                # with POST data. This prevents data from being posted twice if a
                # user hits the Back button.
                return HttpResponseRedirect(reverse("polls:results", args=(question.id,)))



def user_login(request):
    if request.method == 'GET':
        return render(request, "polls/login.html")
    else:
        username = request.POST["username"]
        password = request.POST["password"]

        print(username, password)

        user = authenticate(username=username, password=password)

        if user:
            login(request, user)
            apk = ApiKey.objects.get(username=username)
            return HttpResponseRedirect("/polls/?username={}&api_key={}".format(username, apk.api_key)) # send apk.api_key
        else:
            return render(request, "polls/login.html", context={"error": "wrong login or password"})

def register(request):
    if request.method == 'GET':
        return render(request, "polls/register.html")

    else:
        username = request.POST["username"]
        firstname = request.POST["firstname"]
        lastname = request.POST["lastname"]
        password = request.POST['password']
        
        user = User.objects.create_user(username=username, password=password)
        user.first_name=firstname
        user.last_name=lastname
        user.save()

        PollUser(user=user).save()
        letters = string.ascii_lowercase
        ApiKey(username=user.username, api_key=''.join(random.choice(letters) for i in range(16))).save()

        return HttpResponseRedirect("/polls/login")
    

def log_out(request):
    logout(request)
    return HttpResponseRedirect("/polls/login")

myproject/polls/templates/polls/detail.html
<form action="{% url 'polls:vote' question.id %}" method="post">
{% csrf_token %}
<fieldset>
    <legend><h1>{{ question.question_text }}</h1></legend>
    {% if error_message %}<p><strong>{{ error_message }}</strong></p>{% endif %}
    {% for choice in question.choice_set.all %}
        <input type="radio" name="choice" id="choice{{ forloop.counter }}" value="{{ choice.id }}">
        <label for="choice{{ forloop.counter }}">{{ choice.choice_text }}</label><br>
    {% endfor %}
</fieldset>
<input type="submit" value="Vote">
</form>

myproject/polls/templates/polls/index.html
{% if latest_question_list %}
    <ul>
    {% for question in latest_question_list %}
        <li><a href="/polls/{{ question.id }}/">{{ question.question_text }}</a></li>
    {% endfor %}
    </ul>
{% else %}
    <p>No polls are available.</p>
{% endif %}


{% if user_info %}
<p> {{ user_info }} </p>
<a href="/polls/logout">Logout</a>
{% else %}
<p> Please login to continue </p>
<a href="/polls/user_login">Login</a>
{%endif%}

myproject/polls/templates/polls/login.html
<h1> Welcome to Polls website</h1>


<form action="{% url 'polls:login' %}" method="post">
{% csrf_token %}
  <input type="text" name="username" id="username" value="">
  <input type="password" name="password" id="password" value="">
  <input type="submit" value="Login">
</form>

{%if error %}
  <p> {{ error }}</p>
{% endif %}
<p>Not registered yet?</p> <a href="/polls/register">Register Now</a>

myproject/polls/templates/polls/register.html
<h1> Welcome to registration</h1>


<form action="{% url 'polls:register' %}" method="post">
{% csrf_token %}
  <input type="text" name="firstname" id="firstname" value="" placeholder="Firstname">
  <input type="text" name="lastname" id="lastname" value="">
  <input type="text" name="username" id="username" value="">

  <input type="password" name="password" id="password" value="">
  <input type="password" name="confirm_password" id="confirm_password" value="">
  
  <input type="submit" value="Sign Up">
</form>

myproject/polls/templates/polls/results.html
<h1>{{ question.question_text }}</h1>

<ul>
{% for choice in question.choice_set.all %}
    <li>{{ choice.choice_text }} -- {{ choice.votes }} vote{{ choice.votes|pluralize }}</li>
{% endfor %}
</ul>

<a href="{% url 'polls:detail' question.id %}">Vote again?</a>